config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  get 'dashboard', to: 'pages#dashboard'

 resources :castings, only: [:show, :index, :new, :create, :delete]


  resources :posts, only: [:show, :create, :index]


  mount Thredded::Engine => '/forum'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/casting.rb
class Casting < ApplicationRecord
  has_one_attached :image
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many_attached :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/castings_controller.rb
class CastingsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_casting, only: [:show, :create, :edit, :destroy]

  def index
    @castings = Casting.all
  end

  def show
  end

  def new
    @casting = Casting.new
  end

  def create
    @casting = Casting.new(casting_params)
    if @casting.save
      redirect_to castings_path
    else
      render :new
    end
  end

  def edit
  end

  def destroy
  end

  private

  def set_casting
    @casting = Casting.find(params[:id])
  end

  def casting_params
    params.require(:casting).permit(:title, :content, :city, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :set_user, only: :dashboard

  def dashboard
  end

  def home
  end

  private

  def set_user
    @user = current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.All
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/castings_helper.rb
module CastingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/castings/_form.html.erb
<div class="container">
  <div class="row d-flex justify-content-center my-5 py-5 login-box">
    <div class="col-md-8 border rounded py-4 px-5 shadow">
      <h5 class="text-center mb-4">List Casting</h2>
      <%= simple_form_for @casting do |f| %>
      <%= f.input :title%>
      <%= f.input :content %>
      <%= f.input :city %>
      <%= f.input :image, input_html: { class: 'hidden'} %>
      <%= image_tag "", width: 300, class: "show", id: "photo-preview" %>
      <%= f.submit "Post Casting", class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/castings/edit.html.erb
<%= render "form" %>

app/views/castings/index.html.erb
<h1>All the castings!</h1>


<h3> <%= link_to "Create new casting", new_casting_path %> </h3>

app/views/castings/new.html.erb
new.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marlon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- loads app/javascript/packs/application.js -->
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<H2><%= current_user.fullname %></H2>

<p> <%= link_to "Castings", castings_path %> </p>

<p>Foro</p>

<p>Oportunidades</p>


<%#= Thredded::ApplicationController.render partial: 'thredded/users/posts', locals: {
      posts: Thredded.posts_page_view(scope: User.thredded_posts.order_newest_first.limit(5),
                                      current_user: current_user) } %>

app/views/pages/home.html.erb
<h2> Bienvenidos a Marlon </h2>



<%= link_to "profile", dashboard_path %>

app/views/posts/index.html.erb
index.html.erb

app/views/posts/show.html.erb
show.html.erb

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

    <div class="nav-item active">
      <h3> <%= link_to "Marlon", root_path, class: "nav-link"  %></h3>
    </div>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to current_user.fullname, dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li>
           <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", :method => :delete %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/thredded/shared/nav/_standalone.html.erb
<li class="thredded--user-navigation--standalone--session thredded--user-navigation--item">
  <% resource_name = Thredded.user_class_name.demodulize.underscore %>
  <% if thredded_signed_in? %>
    <%= link_to main_app.send(:"destroy_#{resource_name}_session_path"), method: :delete do %>
      Sign Out
    <% end %>
  <% else %>
    <%= link_to main_app.send(:"new_#{resource_name}_session_path") do %>
      Sign In / Register
    <% end %>
  <% end %>
</li>